import {
  Activity,
  BarChart3,
  BookOpenCheck,
  CalendarCheck,
  CheckCircle2,
  ClipboardCheck,
  Clock3,
  DatabaseZap,
  FileInput,
  Gauge,
  Home,
  Inbox,
  ListChecks,
  MailCheck,
  MailPlus,
  Settings,
  ShieldCheck,
  Sparkles,
  Users,
  Workflow
} from "lucide-react";

export const navigationItems = [
  { label: "Dashboard", href: "/", icon: Home },
  { label: "Lead Discovery", href: "/lead-discovery", icon: Sparkles },
  { label: "Leads", href: "/leads", icon: Users },
  { label: "Import CSV", href: "/import-csv", icon: FileInput },
  { label: "AI Lead Scoring", href: "/ai-lead-scoring", icon: Gauge },
  { label: "Email Verification", href: "/email-verification", icon: MailCheck },
  { label: "Campaigns", href: "/campaigns", icon: Workflow },
  { label: "Campaign Builder", href: "/campaign-builder", icon: ListChecks },
  { label: "Email Builder", href: "/email-builder", icon: MailPlus },
  { label: "Sending Queue", href: "/sending-queue", icon: Clock3 },
  { label: "Replies", href: "/replies", icon: Inbox },
  { label: "Bookings", href: "/bookings", icon: CalendarCheck },
  { label: "GoHighLevel Sync", href: "/ghl-sync", icon: DatabaseZap },
  { label: "Compliance", href: "/compliance", icon: ClipboardCheck },
  { label: "Suppression List", href: "/suppression-list", icon: ShieldCheck },
  { label: "Domain Guard", href: "/domain-guard", icon: CheckCircle2 },
  { label: "Settings", href: "/settings", icon: Settings },
  { label: "Audit Logs", href: "/audit-logs", icon: Activity },
  { label: "Docs", href: "/docs", icon: BookOpenCheck }
];
